language: python
python:
  - "3.8"
sudo: required
dist: trusty
notifications:
  email: false
before_install:
  - pip install codecov
  - pip install coveralls
install:
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-cookies

script:
  - py.test -s -v --cov=.
after_success:
  - codecov
  - coveralls
